# Konfiguracja dla Netlify

[build]
  # Komenda do budowania frontendu
  command = "npm run build"

  # Katalog, w którym znajdują się zbudowane pliki frontendu
  publish = "build"

  # Katalog, w którym znajdują się funkcje serwerowe
  functions = "netlify/functions"

# Przekierowanie zapytań API do funkcji serwerowej
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Reguła "catch-all" dla aplikacji SPA (React Router)
# Musi być na końcu pliku.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200